demonsters/prisma-mock

package.json
src/index.ts
tsconfig.json
yarn.lock

The constructor interface for `PrismaClientKnownRequestError` changed in version 4.7.0 of prisma:
* before: `constructor(message: string, code: string, clientVersion: string, meta?: any)`
* after: `constructor(message: string, { code, clientVersion, meta, batchRequestIdx }: KnownErrorParams)`
This breaks tests in projects using a more recent version of prisma.
This PR aims to support both the old version and the new one.

feat: support newer prisma versions (min 4.7.0)

---

__tests__/update.test.ts
src/index.ts

When calling `update` and the `data` has  a key set to `undefined` the official prisma client will skip these values and leave them unchanged. This update adds that functionality to this package.

fix: ignore undefined values to retain official prisma behavior

---

__tests__/__snapshots__/where.test.ts.snap
__tests__/index.test.ts
prisma/schema.prisma
src/index.ts

Hi
I found issue and implement behavior.
Throw error when create a record with connects via combined-unique index to already exists.
Look-up record by unique index with combined-key after single key look-up failed.

Feature use combined-unique index on connect

---

__tests__/bulk-operations.test.ts
src/index.ts

The actual createMany/updateMany/deleteMany mock implementations didn't respect Prisma. All those operations should return a value of `type BatchOperation = { count: number }` where count is the number of affected records (cf. https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#return-type-7).
I modified existing implementations to make them return the appropriate type.

fix: respect Prisma's createMany/updateMany/deleteMany return type

---

__tests__/__snapshots__/where.test.ts.snap
__tests__/internal-state.test.ts
src/index.ts

It is useful to check that the internal state of the mock client matches an expected snapshot. The `$getInternalState` method on the mock client returns the `data` object for this purpose. This does not result in any 'native' calls, such as `findMany` for each entity.
For example usage, check the included tests.

Get Internal State of Client

---

__tests__/errors.test.ts
__tests__/index.test.ts
src/index.ts

Fix #36, doesn't return error code P2025 for not found errors. Also adds a small improvement to actually report the Prisma client version rather than mocking it.

 Fix #36, doesn't return error code P2025 for not found errors

---

package.json

prisma-mock does not run without jest-mock-extended, so putting it on dependencies allows me to use prisma-mock without having to declare jest-mock-extended on my package.json.

fix: changes jest-mock-extended to dependency, not devDependency

---

__tests__/transaction-api.test.ts
src/index.ts

This fixes the issue for interactive transactions where errors were being silently caught. See https://github.com/demonsters/prisma-mock/issues/44

Propagate error in interactive transactions

---

__tests__/where.test.ts

The current unit test fails on my machine due to the local-timezone-dependant code. 😞

fix: make the test timezone agnostic

---

src/index.ts

The unit test `Referential actions`-`onDelete`-`Cascade` fails while the test doesn't set up all rows of related tables with `Account`.
As I tested against real MySQL 8.0.28, it allows that situation on deletion.
So I thought the mock should do the same.

fix: allow delete against row even if whose related row is absent

---

src/defaults/autoincrement.ts

Currently autoincrement only supports Int and not BigInt. This allows it to support BigInt which is currently limited by the use of Math.max

Fix autoincrement to support BigInt

---

package.json
yarn.lock

We are making a storybook RSC dem using this awesome library to mock out the DB in the browser :)
https://github.com/storybookjs/module-mocking-demo
I bumped jest-mock-extended to make sure it is compatible with TS5:
```sh
 WARN  Issues with peer dependencies found
.
└─┬ prisma-mock 0.10.1
└─┬ jest-mock-extended 2.0.9
└── ✕ unmet peer typescript@"^3.0.0 || ^4.0.0": found 5.4.3
Done in 3.6s
```

Upgrade jest-mock-extended to version 3.0.6

---

__tests__/where.test.ts
src/index.ts

As I tested against `"@prisma/client": "5.14.0"`, it seemed to ignore undefined value in comparison, at least `lt`/`gt` series.
So, the real Prisma can work with the following function.
```typescript
async function findUpcomingMatches({
start = new Date(),
end,
}: {
start?: Date;
end?: Date | undefined;
}): Promise<Match[]> {
return prisma.match.findMany({
where: {
start: {
gte: start,
lt: end, // no limits if the caller doesn't specify `end`.
},
},
take: 3,
orderBy: { start: 'asc' },
});
}
```

fix: comparison with undefined value should be ignored

---

package.json

Hi,
it seems the package.json needs to be updated to allow Prisma 6 clients, hopefully this solves it 👍🏻

Allow Prisma ^6 versions

---

__tests__/nested-one-to-many.test.ts
__tests__/performance.test.ts
package.json
src/index.ts
src/indexes.test.ts
src/indexes.ts

Calling `filter` & `map` on every item gets exponentially slower with a lot of items, especially when you have a lot of "joins".
We fix this by reference items by index (id's, relation fields, etc). The `filter` & `map` is still called, but on a subset of items.
This makes especially joins a lot faster.

Add "indexes" for faster lookup

---

__tests__/bugs.test.ts
__tests__/include.test.ts
package.json
prisma/schema.prisma
src/delegate.ts
src/index.ts
src/utils/fieldHelpers.ts
yarn.lock

Refactor default value handling by renaming isFieldDefault for clarity.
Fix unique constraint logic to only consider ID fields when building where clauses.
Add support for composite unique indexes in the Stripe model schema.
Update dependencies to include ts-essentials and jest-mock-extended.
Add test case to verify create operation returns null correctly.
Clean up unused code and imports for better maintainability.

feat(delegate): improve default handling and unique constraints

---

.changeset/config.json

Remove the "access": "restricted" setting from the changeset
configuration to allow broader access. This change simplifies the
configuration and aligns with updated project access policies.

chore(config): remove restricted access from changeset config

---

.changeset/khaki-wombats-swim.md
__tests__/createPrismaClient.ts
__tests__/performance.test.ts
src/indexes.ts

Enable indexes by default in the Prisma mock client to improve query
performance and accuracy in tests. Update index update logic to exclude
the current field from ID field filtering, preventing incorrect item
overwrites. Also, activate the previously skipped performance test to
validate these changes.

test: fix indexes

---

.changeset/forty-papers-bet.md
__tests__/nested-one-to-many.test.ts
__tests__/nested-one-to-one.test.ts
__tests__/update.test.ts
src/delegate.ts

Update delegate nested-update logic to treat non-list relations as
one-to-one and merge provided nested update where-clauses with the
relationship-derived where condition using an AND. This fixes cases
where nested updates could overwrite or ignore relationship constraints
and ensures the correct record is targeted for updates.
Refactor and reformat nested one-to-one tests:
- Replace mixed quotes and formatting inconsistencies with consistent
double quotes and trailing commas.
- Adjust test fixtures and expectations to reflect the updated nested
update behavior (including snapshot updates).
- Rename and repurpose tests to cover update in both directions and
explicit disconnect behavior, and re-enable previously skipped cases.
Overall this addresses incorrect relation handling for singular …

fix: correctly handle nested one-to-one updates and tidy tests

---

.changeset/modern-planets-fail.md
__tests__/bugs.test.ts
src/delegate.ts
src/utils/queryMatching.ts

Add new integration test "every in where" to validate querying with
posts.every conditions and ensure correct mock behavior. Clean up minor
formatting in existing tests.
Refactor createMatch and Delegate wiring to pass a getDelegateForFieldName
helper instead of a generic Delegate parameter. Use that helper to
resolve related model delegates by field name. Fix the "every" handling:
treat an empty set of related records as vacuously true (return true
when all.length === 0) and ensure findMany uses the delegate for
correct comparisons.
These changes fix incorrect evaluation of every filters on relations
and make delegate resolution explicit and safer for nested queries.

feat(tests+query): every-in-where test and fix 'every' logic
